### PR TITLE
LABS-434 Sliding windows without caching inputs

### PR DESCRIPTION
**Pull request by Z-Shang**

### CODE REVIEW

**Review by michaelcahill — COMMENTED** [review]
I think I understand this change and from what I've seen so far it looks like what I was expecting.

My main question is does this code replace the existing sliding window implementation? If not, why not? If so, why isn't the existing code removed?

**Comment by Z-Shang** [comment]
@michaelcahill sure, they can be removed, I've left them there just for run some comparison between the two approaches

**Comment by steve-1820** [comment]
@Z-Shang Before this is merged, has the JS tests been fixed for windows? (https://jira.mongodb.org/browse/LABS-437)

I'd be more comfortable merging this once LABS-437 is completed and we've verified that the old + new implementation pass the existing tests.

**Comment by Z-Shang** [comment]
@steve-1820 no, LABS-437 is not included in this PR

**Comment by steve-1820** [comment]
Ok @Z-Shang - otherwise code looks good.

How do you feel about fixing LABS-437 first before merging this PR?

**Review by steve-1820 — APPROVED** [review]
lgtm

**Pull request merged**
